version: '3.7'

services:

 frontend:

   image: frontend:${APP_VERSION}

 
  ports:
   
   -  target: 3000

      published: 3000

      protocol: tcp

 backend:

   image: backend:${APP_VERSION}

   ports:

   -  target: 8080

      published: 8080

      protocol: tcp