version: '3.7'
services:
 frontend:
   build: './SoloProj-frontend/soloproject-fe/'
   image: frontend:v1.3
   ports:
   -  target: 3000
      published: 3000
      protocol: tcp
 backend:
   build: './SoloProj-backend/soloproject-be/'
   image: backend:v1.3
   ports:
   -  target: 8080
      published: 8080
      protocol: tcp